name: CI

on:
  push:
    branches: [main]
    tags: ["v*"]
  pull_request:
    branches: ["*"]

env:
  CARGO_TERM_COLOR: always

jobs:
  all:
    name: All
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions-rust-lang/setup-rust-toolchain@v1

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -qq --no-install-recommends \
          ffmpeg \
          libavcodec-dev \
          libavdevice-dev \
          libavfilter-dev \
          libavformat-dev \
          libavutil-dev \
          libprotobuf-dev \
          libswscale-dev \
          protobuf-compiler

    - name: Check formatting
      run: cargo fmt --all -- --check

    - name: Build
      run: cargo build --verbose

    - name: Run clippy
      run: cargo clippy -- -D warnings

    - name: Run tests
      run: cargo test --verbose
